# Feature Engineering. Практическая работа

Сдаётся на проверку.

## Цели практической работы

Научиться: 

*   генерировать новые признаки; 
*   нормализовать и кодировать данные с помощью lambda-функций и библиотеки scikit-learn.

## Что входит в практическую работу

1. Построить признаки из строк.
2. Преобразовать категориальные переменные.
3. Стандартизировать данные.
4. Использовать MinMaxScaler для нормализации данных.
5. Создать признаки на основе дат.
6. Сохранить датафрейм для этапа моделирования.

## Что оценивается
- Программа выдаёт верный ответ на заданном наборе данных.
- Описаны причины выбранного решения, если требуется.
- Код читабелен: переменным даны осмысленные названия, соблюдены отступы и правила расстановки пробелов.
- При построении графиков название и оси подписаны, выведена легенда, если требуется. 
- Репозиторий проекта содержит осмысленные коммиты, содержащие конкретные реализованные фичи, ветки названы согласно назначению, лишние файлы не хранятся в репозитории.
- В репозитории проекта соблюдена иерархия директорий согласно списку модулей и содержащихся в них тем.
- Репозиторий проекта содержит файлы с данными, полученными в результате выполнения практической работы.

## Как отправить работу на проверку
Сдайте практическую работу этого модуля через систему контроля версий Git сервиса Skillbox GitLab. После загрузки работы на проверку напишите об этом в личном кабинете своему проверяющему куратору.

## Задача

Мы продолжим исследовать и готовить данные для этапа моделирования.

Вам предстоит работать с небольшой выборкой из коллекции подержанных автомобилей, выставленных на продажу в Соединённых Штатах, представленной в файле `data/vehicles_dataset_upd.csv`. На этих данных вы построите первую модель классификации, определяющую категорию цены подержанного автомобиля в зависимости от характеристик транспортного средства.

В этой практической работе вы продолжите генерировать дополнительные признаки и завершите подготовку датасета для этапа моделирования.

## Описание датасета:
- `id`— идентификатор записи;
- `url`— URL-записи о продаже;
- `region`— регион;
- `region_url`— URL региона;
- `price`— стоимость;
- `year`— год выпуска;
- `manufacturer`— производитель;
- `model`— модель;
- `condition`— состояние;
- `cylinders`— количество цилиндров;
- `fuel`— тип топлива;
- `odometer`— количество пройденных миль;
- `title_status`— статус;
- `transmission`— коробка передач;
- `VIN`— идентификационный номер;
- `drive`— тип привода;
- `size`— размер;
- `type`— кузов;
- `paint_color`— цвет;
- `image_url`— URL изображения;
- `description`— указанное описание;
- `county`— страна;
- `state`— штат;
- `lat`— широта;
- `long`— долгота;
- `posting_date`— дата размещения объявления о продаже;
- `price_category`— категория цены.

In [1]:
# Импортируйте необходимые библиотеки
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import (
    OneHotEncoder, 
    StandardScaler, 
    MinMaxScaler
)

### Задача 1. Построение признаков из строк

1. Загрузите датасет из `data/vehicles_dataset_upd6.csv`, выведите первые пять записей и список колонок.

In [3]:
# Ваш код здесь
df = pd.read_csv('data/vehicles_dataset_upd6.csv')
df.head()

,id,url,region,region_url,price,year,manufacturer,model,fuel,odometer,...,is_jeep,is_honda,is_nissan,x0_diesel,x0_electric,x0_gas,x0_hybrid,x0_other,std_scaled_odometer,std_scaled_price
0,7308295377,https://chattanooga.craigslist.org/ctd/d/chatt...,chattanooga,https://chattanooga.craigslist.org,54990,2020,ram,2500 crew cab big horn,diesel,27442,...,0,0,0,1.0,0.0,0.0,0.0,0.0,-1.079390,2.958509
1,7316380095,https://newjersey.craigslist.org/ctd/d/carlsta...,north jersey,https://newjersey.craigslist.org,16942,2016,ford,explorer 4wd 4dr xlt,other,60023,...,0,0,0,0.0,0.0,0.0,0.0,1.0,-0.560115,-0.085826
2,7313733749,https://reno.craigslist.org/ctd/d/atlanta-2017...,reno / tahoe,https://reno.craigslist.org,35590,2017,volkswagen,golf r hatchback,gas,14048,...,0,0,0,0.0,0.0,1.0,0.0,0.0,-1.292863,1.406256
3,7308210929,https://fayetteville.craigslist.org/ctd/d/rale...,fayetteville,https://fayetteville.craigslist.org,14500,2013,toyota,rav4,gas,117291,...,0,0,0,0.0,0.0,1.0,0.0,0.0,0.352621,-0.281218
4,7303797340,https://knoxville.craigslist.org/ctd/d/knoxvil...,knoxville,https://knoxville.craigslist.org,14590,2012,bmw,1 series 128i coupe 2d,other,80465,...,0,0,0,0.0,0.0,0.0,0.0,1.0,-0.234311,-0.274017

2. Выведите список значений и количество уникальных значений для модели автомобиля.

In [5]:
# Ваш код здесь
print(df.model.nunique())
print(list(df.model.unique()))

3341

3. Количество уникальных значений велико. Попробуем их сократить, оставив только первое слово в наименовании модели. С помощью lambda-функции и преобразования над строками создайте новый признак `short_model`, содержащий только первое слово из наименования модели, выведите его и количество получившихся уникальных значений.

In [7]:
# Ваш код здесь
df['short_model'] = df.model.apply(lambda x: x.split()[0])
df['short_model']

0           2500
1       explorer
2           golf
3           rav4
4              1
          ...
9614        rav4
9615    wrangler
9616          a3
9617     cayenne
9618        1500
Name: short_model, Length: 9619, dtype: object

In [9]:
df['short_model'].nunique()

943

### Задача 2. Преобразование категориальных переменных

1. Для категориальных переменных `short_model`, `transmission`, `region`, `manufacturer`, `state`, `title_status`, `age_category` распечатайте наименование категории и количество уникальных значений в ней.

In [11]:
# Ваш код здесь
cat_columns = ['short_model', 'transmission', 'region', 'manufacturer', 'state', 'title_status', 'age_category']

for column in cat_columns:
    print(column, df[column].nunique())

short_model 943
transmission 3
region 393
manufacturer 40
state 51
title_status 6
age_category 3

2. Создайте датафрейм `data`, содержащий только выбранные категориальные переменные.

In [13]:
# Ваш код здесь
data = df[['short_model', 'transmission', 'region', 'manufacturer', 'state', 'title_status', 'age_category']]
data

,short_model,transmission,region,manufacturer,state,title_status,age_category
0,2500,other,chattanooga,ram,tn,clean,new
1,explorer,automatic,north jersey,ford,nj,clean,new
2,golf,other,reno / tahoe,volkswagen,ca,clean,new
3,rav4,automatic,fayetteville,toyota,nc,clean,average
4,1,other,knoxville,bmw,tn,clean,average
...,...,...,...,...,...,...,...
9614,rav4,automatic,chautauqua,toyota,ny,clean,old
9615,wrangler,other,binghamton,jeep,ny,clean,average
9616,a3,automatic,salem,audi,or,clean,average
9617,cayenne,automatic,madison,porsche,wi,clean,new
9618,1500,other,norfolk / hampton roads,ram,va,clean,new

3. Создайте объект класса OneHotEncoder, который будет отвечать за преобразование. Уточните, что на выходе должна быть неразреженная матрица.

In [15]:
# Ваш код здесь
ohe = OneHotEncoder(sparse_output=False)
ohe

OneHotEncoder(sparse_output=False)

4. Идентифицируйте параметры преобразования на датафрейме с категориальными переменными.

In [17]:
# Ваш код здесь
ohe.fit(data)

OneHotEncoder(sparse_output=False)

5. Примените преобразование для датафрейма с категориальными переменными и сохраните в новую переменную, распечатайте получившуюся матрицу и её размерность.

In [19]:
# Ваш код здесь
data_encoded = ohe.transform(data)

encoded_columns = ohe.get_feature_names_out(data.columns)
data_encoded_df = pd.DataFrame(data_encoded, columns=encoded_columns)

print("Размерность закодированной матрицы:", data_encoded.shape)
data_encoded_df.head()

Размерность закодированной матрицы: (9619, 1439)

,short_model_-benz,short_model_1,short_model_124,short_model_128i,short_model_135i,short_model_1500,short_model_163869,short_model_1928,short_model_1951,short_model_1954,...,state_wy,title_status_clean,title_status_lien,title_status_missing,title_status_parts only,title_status_rebuilt,title_status_salvage,age_category_average,age_category_new,age_category_old
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

6. Выведите новые наименования признаков с помощью метода `get_feature_names_out`.

In [21]:
# Ваш код здесь
encoded_features = ohe.get_feature_names_out(input_features=data.columns)
encoded_features

array(['short_model_-benz', 'short_model_1', 'short_model_124', ...,
       'age_category_average', 'age_category_new', 'age_category_old'],
      dtype=object)

7. Добавьте в исходный датафрейм получившиеся новые признаки, выведите первые пять записей датафрейма и список колонок.

In [23]:
# Ваш код здесь
df = pd.concat([df, data_encoded_df], axis=1)
df.shape

(9619, 1485)

8. Посмотрите на результат обратного преобразования получившейся матрицы в исходные признаки, используйте `inverse_transform`.

In [25]:
# Ваш код здесь
ohe.inverse_transform(data_encoded)

array([['2500', 'other', 'chattanooga', ..., 'tn', 'clean', 'new'],
       ['explorer', 'automatic', 'north jersey', ..., 'nj', 'clean',
        'new'],
       ['golf', 'other', 'reno / tahoe', ..., 'ca', 'clean', 'new'],
       ...,
       ['a3', 'automatic', 'salem', ..., 'or', 'clean', 'average'],
       ['cayenne', 'automatic', 'madison', ..., 'wi', 'clean', 'new'],
       ['1500', 'other', 'norfolk / hampton roads', ..., 'va', 'clean',
        'new']], dtype=object)

### Задача 3. Стандартизация данных

1. Создайте переменную под количественные переменные `lat`, `long`, `year`, `odometer/price`, `desc_len`, `model_in_desc`, `model_len`, `model_word_count` и создайте датафрейм `data`, содержащий только выбранные количественные переменные.

In [27]:
# Ваш код здесь
quantitive_var = [
    'lat', 'long', 'year', 'odometer/price', 'desc_len',
    'model_in_desc', 'model_len', 'model_word_count'
] 
data = df[quantitive_var].copy()
data.head()

,lat,long,year,odometer/price,desc_len,model_in_desc,model_len,model_word_count
0,35.060000,-85.250000,2020,0.499036,4482,0,22,5
1,40.821805,-74.061962,2016,3.542852,968,0,20,4
2,33.779214,-84.411811,2017,0.394718,4286,0,16,3
3,35.715954,-78.655304,2013,8.089034,3241,0,4,1
4,35.970000,-83.940000,2012,5.515079,4851,0,22,5

2. Создайте объект `std_scaler` класса StandardScaler с параметрами по умолчанию, который будет отвечать за стандартизацию.

In [29]:
# Ваш код здесь
std_scaler = StandardScaler()
std_scaler

StandardScaler()

3. Идентифицируйте параметры преобразования на датафрейме с количественными переменными.

In [31]:
# Ваш код здесь
std_scaler.fit(data)

StandardScaler()

4. Примените преобразование для датафрейма с количественными переменными и сохраните в новую переменную, распечатайте получившуюся матрицу и её размерность.

In [33]:
# Ваш код здесь
scaled_data = std_scaler.transform(data)
print(scaled_data)
print(scaled_data.shape)

[[-0.61917248  0.48424452  1.32239376 ... -0.15578836  1.16303238
   1.91066901]
 [ 0.38801429  1.11079989  0.69597272 ... -0.15578836  0.93208734
   1.23579936]
 [-0.84305905  0.531185    0.85257798 ... -0.15578836  0.47019727
   0.56092971]
 ...
 [ 1.10542805 -1.62887477 -0.08705357 ... -0.15578836  1.50944993
   1.91066901]
 [ 0.7739386   0.25195859  0.53936746 ... -0.15578836 -0.56905538
  -0.78880959]
 [-0.33773799  0.98546471  0.85257798 ... -0.15578836  1.16303238
   1.91066901]]
(9619, 8)

5. Создайте наименования новых признаков по шаблону: `lat_std` для `lat` и так далее.

In [35]:
# Ваш код здесь
new_columns = [f"{col}_std" for col in data.columns]

scaled_df = pd.DataFrame(scaled_data, columns=new_columns)
scaled_df.head()

,lat_std,long_std,year_std,odometer/price_std,desc_len_std,model_in_desc_std,model_len_std,model_word_count_std
0,-0.619172,0.484245,1.322394,-0.510784,0.632075,-0.155788,1.163032,1.910669
1,0.388014,1.110800,0.695973,-0.402947,-0.646781,-0.155788,0.932087,1.235799
2,-0.843059,0.531185,0.852578,-0.514480,0.560744,-0.155788,0.470197,0.560930
3,-0.504509,0.853562,0.226157,-0.241883,0.180435,-0.155788,-0.915473,-0.788810
4,-0.460101,0.557607,0.069552,-0.333074,0.766366,-0.155788,1.163032,1.910669

6. Добавьте в исходный датафрейм получившиеся новые признаки, выведите первые пять записей датафрейма и список колонок.

In [37]:
# Ваш код здесь
df = pd.concat([df, scaled_df], axis=1)
df.head()

,id,url,region,region_url,price,year,manufacturer,model,fuel,odometer,...,age_category_new,age_category_old,lat_std,long_std,year_std,odometer/price_std,desc_len_std,model_in_desc_std,model_len_std,model_word_count_std
0,7308295377,https://chattanooga.craigslist.org/ctd/d/chatt...,chattanooga,https://chattanooga.craigslist.org,54990,2020,ram,2500 crew cab big horn,diesel,27442,...,1.0,0.0,-0.619172,0.484245,1.322394,-0.510784,0.632075,-0.155788,1.163032,1.910669
1,7316380095,https://newjersey.craigslist.org/ctd/d/carlsta...,north jersey,https://newjersey.craigslist.org,16942,2016,ford,explorer 4wd 4dr xlt,other,60023,...,1.0,0.0,0.388014,1.110800,0.695973,-0.402947,-0.646781,-0.155788,0.932087,1.235799
2,7313733749,https://reno.craigslist.org/ctd/d/atlanta-2017...,reno / tahoe,https://reno.craigslist.org,35590,2017,volkswagen,golf r hatchback,gas,14048,...,1.0,0.0,-0.843059,0.531185,0.852578,-0.514480,0.560744,-0.155788,0.470197,0.560930
3,7308210929,https://fayetteville.craigslist.org/ctd/d/rale...,fayetteville,https://fayetteville.craigslist.org,14500,2013,toyota,rav4,gas,117291,...,0.0,0.0,-0.504509,0.853562,0.226157,-0.241883,0.180435,-0.155788,-0.915473,-0.788810
4,7303797340,https://knoxville.craigslist.org/ctd/d/knoxvil...,knoxville,https://knoxville.craigslist.org,14590,2012,bmw,1 series 128i coupe 2d,other,80465,...,0.0,0.0,-0.460101,0.557607,0.069552,-0.333074,0.766366,-0.155788,1.163032,1.910669

### Задача 4. MinMax-нормализация данных

1. Импортируйте MinMaxScaler из `sklearn.preprocessing`.

In [39]:
# Ваш код здесь
from sklearn.preprocessing import MinMaxScaler

2. Создайте датафрейм, содержащий переменные `lat` и `long`.

In [41]:
# Ваш код здесь
coords_df = df[['lat', 'long']].copy()
coords_df.head()

         lat       long
0  35.060000 -85.250000
1  40.821805 -74.061962
2  33.779214 -84.411811
3  35.715954 -78.655304
4  35.970000 -83.940000

3. Повторите действия пунктов 2–6 из задачи 3 для добавления в исходный датафрейм признаков `lat_mm` и `long_mm`. Выведите получившийся датафрейм.

In [43]:
# Ваш код здесь
mm = MinMaxScaler()
mm

MinMaxScaler()

In [45]:
mm.fit(coords_df)

MinMaxScaler()

In [47]:
scaled_coords = mm.transform(coords_df)
scaled_coords

array([[0.34176874, 0.28869912],
       [0.4686646 , 0.33305517],
       [0.31356118, 0.2920222 ],
       ...,
       [0.55905185, 0.13910399],
       [0.51728736, 0.27225478],
       [0.37722678, 0.32418225]])

In [49]:
scaled_coords_df = pd.DataFrame(
    scaled_coords, 
    columns=['lat_mm', 'long_mm'],
    index=coords_df.index
)
scaled_coords_df.head()

     lat_mm   long_mm
0  0.341769  0.288699
1  0.468665  0.333055
2  0.313561  0.292022
3  0.356215  0.314844
4  0.361810  0.293893

In [51]:
df = pd.concat([df, scaled_coords_df], axis=1)
df.head()

,id,url,region,region_url,price,year,manufacturer,model,fuel,odometer,...,lat_std,long_std,year_std,odometer/price_std,desc_len_std,model_in_desc_std,model_len_std,model_word_count_std,lat_mm,long_mm
0,7308295377,https://chattanooga.craigslist.org/ctd/d/chatt...,chattanooga,https://chattanooga.craigslist.org,54990,2020,ram,2500 crew cab big horn,diesel,27442,...,-0.619172,0.484245,1.322394,-0.510784,0.632075,-0.155788,1.163032,1.910669,0.341769,0.288699
1,7316380095,https://newjersey.craigslist.org/ctd/d/carlsta...,north jersey,https://newjersey.craigslist.org,16942,2016,ford,explorer 4wd 4dr xlt,other,60023,...,0.388014,1.110800,0.695973,-0.402947,-0.646781,-0.155788,0.932087,1.235799,0.468665,0.333055
2,7313733749,https://reno.craigslist.org/ctd/d/atlanta-2017...,reno / tahoe,https://reno.craigslist.org,35590,2017,volkswagen,golf r hatchback,gas,14048,...,-0.843059,0.531185,0.852578,-0.514480,0.560744,-0.155788,0.470197,0.560930,0.313561,0.292022
3,7308210929,https://fayetteville.craigslist.org/ctd/d/rale...,fayetteville,https://fayetteville.craigslist.org,14500,2013,toyota,rav4,gas,117291,...,-0.504509,0.853562,0.226157,-0.241883,0.180435,-0.155788,-0.915473,-0.788810,0.356215,0.314844
4,7303797340,https://knoxville.craigslist.org/ctd/d/knoxvil...,knoxville,https://knoxville.craigslist.org,14590,2012,bmw,1 series 128i coupe 2d,other,80465,...,-0.460101,0.557607,0.069552,-0.333074,0.766366,-0.155788,1.163032,1.910669,0.361810,0.293893

4. Создайте переменную под географические признаки `lat`, `lat_std`, `lat_mm`, `long`, `long_std`, `long_mm` и выведите их. Посмотрите на различия в значениях для исходных признаков и нормализованных с помощью стандартизации и MinMax-преобразования.

In [53]:
# Ваш код здесь
geo_feat = ['lat', 'lat_std', 'lat_mm', 'long', 'long_std', 'long_mm']
df[geo_feat].head()

         lat   lat_std    lat_mm       long  long_std   long_mm
0  35.060000 -0.619172  0.341769 -85.250000  0.484245  0.288699
1  40.821805  0.388014  0.468665 -74.061962  1.110800  0.333055
2  33.779214 -0.843059  0.313561 -84.411811  0.531185  0.292022
3  35.715954 -0.504509  0.356215 -78.655304  0.853562  0.314844
4  35.970000 -0.460101  0.361810 -83.940000  0.557607  0.293893

5. Выведите описательные статистики для всех географических признаков. Посмотрите на различия в статистиках для исходных признаков и нормализованных с помощью стандартизации и MinMax-преобразования.

In [57]:
# Ваш код здесь
df[geo_feat].describe().T

,count,mean,std,min,25%,50%,75%,max
lat,9619.0,3.860209e+01,5.720989,19.541726,34.920000,39.300000,42.382100,64.947500
lat_std,9619.0,2.105257e-16,1.000052,-3.331829,-0.643645,0.121997,0.660760,4.605283
lat_mm,9619.0,4.197785e-01,0.125997,0.000000,0.338685,0.435149,0.503028,1.000000
long,9619.0,-9.389688e+01,17.857352,-158.069300,-106.944340,-87.845800,-80.678711,94.163200
long_std,9619.0,-4.498602e-16,1.000052,-3.593801,-0.730687,0.338874,0.740247,10.531788
long_mm,9619.0,2.544177e-01,0.070797,0.000000,0.202690,0.278408,0.306822,1.000000

6. Выведите матрицу корреляций для всех географических признаков, чтобы убедиться, что нормализация признаков сохранила свойства исходных признаков.

In [61]:
# Ваш код здесь
correlation_matrix = df[geo_feat].corr()
correlation_matrix

               lat   lat_std    lat_mm      long  long_std   long_mm
lat       1.000000  1.000000  1.000000 -0.134596 -0.134596 -0.134596
lat_std   1.000000  1.000000  1.000000 -0.134596 -0.134596 -0.134596
lat_mm    1.000000  1.000000  1.000000 -0.134596 -0.134596 -0.134596
long     -0.134596 -0.134596 -0.134596  1.000000  1.000000  1.000000
long_std -0.134596 -0.134596 -0.134596  1.000000  1.000000  1.000000
long_mm  -0.134596 -0.134596 -0.134596  1.000000  1.000000  1.000000

### Задача 5. Признаки на основе дат

1. Выведите по отдельности колонки `posting_date` и `date`.

In [63]:
# Ваш код здесь
print(df['posting_date'].head())
print(df['date'].head())

0    2021-04-17T12:30:50-0400
1    2021-05-03T15:40:21-0400
2    2021-04-28T03:52:20-0700
3    2021-04-17T10:08:57-0400
4    2021-04-08T15:10:56-0400
Name: posting_date, dtype: object
0    2021-04-17 16:30:50+00:00
1    2021-05-03 19:40:21+00:00
2    2021-04-28 10:52:20+00:00
3    2021-04-17 14:08:57+00:00
4    2021-04-08 19:10:56+00:00
Name: date, dtype: object

2. Ранее преобразованная колонка `date` после сохранения в файл и загрузки из него содержит данные в строковом формате, поэтому измените её тип c помощью `pd.to_datetime`.

In [65]:
# Ваш код здесь
df['date'] = pd.to_datetime(df['date'])

3. Несколькими способами извлеките номер месяца продажи автомобиля.

3.1. Из переменной `posting_date` с помощью lambda-функции и операций над строками.

In [71]:
# Ваш код здесь
df['posting_month_str'] = df['posting_date'].apply(lambda x: x.split('-')[1])
df['posting_month_str']

0       04
1       05
2       04
3       04
4       04
        ..
9614    04
9615    05
9616    04
9617    04
9618    04
Name: posting_month_str, Length: 9619, dtype: object

3.2. Из переменной `date` с помощью lambda-функции и метода `month`.

In [69]:
# Ваш код здесь
df['date_month'] = df['date'].apply(lambda x: x.month)
df['date_month']

0       4
1       5
2       4
3       4
4       4
       ..
9614    4
9615    5
9616    4
9617    4
9618    4
Name: date_month, Length: 9619, dtype: int64

3.3. Из переменной `date` с помощью `dt` и метода `month`.

In [73]:
# Ваш код здесь
df['date_month'] = df['date'].dt.month
df['date_month']

0       4
1       5
2       4
3       4
4       4
       ..
9614    4
9615    5
9616    4
9617    4
9618    4
Name: date_month, Length: 9619, dtype: int32

4. Создайте любым из способов (3.2 или 3.3) признак `month`, обозначающий номер месяца размещения объявления о продаже автомобиля, и распечатайте его.

In [75]:
# Ваш код здесь
df['month'] = df['date'].dt.month
df['month']

0       4
1       5
2       4
3       4
4       4
       ..
9614    4
9615    5
9616    4
9617    4
9618    4
Name: month, Length: 9619, dtype: int32

5. Создайте признак `dayofweek`, обозначающий день недели размещения объявления о продаже автомобиля, и распечатайте его.

In [77]:
# Ваш код здесь
df['dayofweek'] = df['date'].dt.dayofweek
df['dayofweek']

0       5
1       0
2       2
3       5
4       3
       ..
9614    5
9615    0
9616    3
9617    2
9618    5
Name: dayofweek, Length: 9619, dtype: int32

6. Создайте признак `diff_years`, обозначающий количество лет между годом производства автомобиля и годом размещения объявления о продаже автомобиля, и распечатайте его. Дополнительные корректировки не применяйте.

In [79]:
# Ваш код здесь
df['diff_years'] = df['date'].dt.year - df['year']
df['diff_years']

0        1
1        5
2        4
3        8
4        9
        ..
9614    19
9615    13
9616    10
9617     6
9618     4
Name: diff_years, Length: 9619, dtype: int64

7. Примените стандартизацию к новым признаками и сохраните результат в новые признаки вида `month_std`.

In [87]:
# Ваш код здесь
date_feat_df = df[['month', 'dayofweek', 'diff_years']].copy()
date_feat_scaled = std_scaler.fit_transform(date_feat_df)

date_feat_scaled_df = pd.DataFrame(
    date_feat_scaled,
    columns=[f'{col}_std' for col in date_feat_df.columns],
    index=date_feat_df.index
)

date_feat_scaled_df.head()

   month_std  dayofweek_std  diff_years_std
0  -0.615846       1.120284       -1.322394
1   1.623784      -1.374972       -0.695973
2  -0.615846      -0.376870       -0.852578
3  -0.615846       1.120284       -0.226157
4  -0.615846       0.122182       -0.069552

In [91]:
df = pd.concat([df, date_feat_scaled_df], axis=1)

df.head()

,id,url,region,region_url,price,year,manufacturer,model,fuel,odometer,...,date_month,month,dayofweek,diff_years,month_std,dayofweek_std,diff_years_std,month_std,dayofweek_std,diff_years_std
0,7308295377,https://chattanooga.craigslist.org/ctd/d/chatt...,chattanooga,https://chattanooga.craigslist.org,54990,2020,ram,2500 crew cab big horn,diesel,27442,...,4,4,5,1,-0.615846,1.120284,-1.322394,-0.615846,1.120284,-1.322394
1,7316380095,https://newjersey.craigslist.org/ctd/d/carlsta...,north jersey,https://newjersey.craigslist.org,16942,2016,ford,explorer 4wd 4dr xlt,other,60023,...,5,5,0,5,1.623784,-1.374972,-0.695973,1.623784,-1.374972,-0.695973
2,7313733749,https://reno.craigslist.org/ctd/d/atlanta-2017...,reno / tahoe,https://reno.craigslist.org,35590,2017,volkswagen,golf r hatchback,gas,14048,...,4,4,2,4,-0.615846,-0.376870,-0.852578,-0.615846,-0.376870,-0.852578
3,7308210929,https://fayetteville.craigslist.org/ctd/d/rale...,fayetteville,https://fayetteville.craigslist.org,14500,2013,toyota,rav4,gas,117291,...,4,4,5,8,-0.615846,1.120284,-0.226157,-0.615846,1.120284,-0.226157
4,7303797340,https://knoxville.craigslist.org/ctd/d/knoxvil...,knoxville,https://knoxville.craigslist.org,14590,2012,bmw,1 series 128i coupe 2d,other,80465,...,4,4,3,9,-0.615846,0.122182,-0.069552,-0.615846,0.122182,-0.069552

### Задача 6. Сохранение датафрейма для этапа моделирования

1. Удалите колонки, которые были исходными для формирования признаков, а также новые признаки, которые были добавлены с целью обучения.  Сохраните новый датафрейм в переменную `df_prepared`.

In [93]:
# Допишите код

columns_for_drop = ['year', 'url', 'region', 'region_url', 'manufacturer',
                    'model', 'fuel', 'odometer', 'title_status', 'transmission',
                    'image_url', 'description', 'state', 'lat', 'long', 'posting_date',
                    'odometer_km', 'odometer/price', 'region_new', 'region_corrected', 'manufacturer_model',
                    'desc_len', 'model_in_desc', 'price_k$', 'age_category', 'model_len', 'model_word_count',
                    'short_model', 'lat_mm', 'long_mm', 'date', 'std_scaled_price',
                    'month', 'dayofweek', 'diff_years',
                    'odometer/price_std']

df_prepared = df.drop(columns=columns_for_drop)

2. Распечатайте оставшийся список колонок и размерность финального датафрейма.

In [95]:
# Ваш код здесь
df_prepared.columns.tolist()

['id',
 'price',
 'price_category',
 'is_audi',
 'is_ford',
 'is_chevrolet',
 'is_toyota',
 'is_jeep',
 'is_honda',
 'is_nissan',
 'x0_diesel',
 'x0_electric',
 'x0_gas',
 'x0_hybrid',
 'x0_other',
 'std_scaled_odometer',
 'short_model_-benz',
 'short_model_1',
 'short_model_124',
 'short_model_128i',
 'short_model_135i',
 'short_model_1500',
 'short_model_163869',
 'short_model_1928',
 'short_model_1951',
 'short_model_1954',
 'short_model_1960s',
 'short_model_1966',
 'short_model_1968',
 'short_model_1972',
 'short_model_1977',
 'short_model_1978',
 'short_model_198.5',
 'short_model_1988',
 'short_model_1994',
 'short_model_1999',
 'short_model_2',
 'short_model_200',
 'short_model_2000',
 'short_model_2002',
 'short_model_2006',
 'short_model_2007',
 'short_model_2008',
 'short_model_2009',
 'short_model_2012',
 'short_model_2015',
 'short_model_2016',
 'short_model_2017',
 'short_model_2018',
 'short_model_210',
 'short_model_240',
 'short_model_2500',
 'short_model_2500hd',
 'short_model_280zx',
 'short_model_3',
 'short_model_3-series',
 'short_model_3-window',
 'short_model_3.2',
 'short_model_300',
 'short_model_300-series',
 'short_model_300c',
 'short_model_300s',
 'short_model_300zx',
 'short_model_3100',
 'short_model_318i',
 'short_model_320i',
 'short_model_323i',
 'short_model_325ci',
 'short_model_325i',
 'short_model_325is',
 'short_model_325xi',
 'short_model_328',
 'short_model_328ci',
 'short_model_328d',
 'short_model_328i',
 'short_model_328xi',
 'short_model_330i',
 'short_model_330xi',
 'short_model_335i',
 'short_model_335xi',
 'short_model_350',
 'short_model_3500',
 'short_model_3500hd',
 'short_model_350z',
 'short_model_370z',
 'short_model_380sl',
 'short_model_3i',
 'short_model_4',
 'short_model_4-runner',
 'short_model_428',
 'short_model_430i',
 'short_model_435i',
 'short_model_440xi',
 'short_model_4500',
 'short_model_4runner',
 'short_model_4x4',
 'short_model_5',
 'short_model_5-series',
 'short_model_50',
 'short_model_500',
 'short_model_500c',
 'short_model_500l',
 'short_model_500x',
 'short_model_525i',
 'short_model_528i',
 'short_model_528xi',
 'short_model_530',
 'short_model_530i',
 'short_model_535i',
 'short_model_535xi',
 'short_model_540i',
 'short_model_545i',
 'short_model_5500',
 'short_model_5500hd',
 'short_model_550i',
 'short_model_5th',
 'short_model_6',
 'short_model_640',
 'short_model_645ci',
 'short_model_650i',
 'short_model_650xi',
 'short_model_7',
 'short_model_750',
 'short_model_750i',
 'short_model_750xi',
 'short_model_86',
 'short_model_911',
 'short_model_914',
 'short_model_928',
 'short_model_944',
 'short_model_ACURA*',
 'short_model_ALL',
 'short_model_AM',
 'short_model_AMC',
 'short_model_ASC',
 'short_model_Acuarea',
 'short_model_American',
 'short_model_BUY',
 'short_model_Bentley',
 'short_model_Blue',
 'short_model_Buicks',
 'short_model_C',
 'short_model_CHEVORLET',
 'short_model_CLICK',
 'short_model_Champion',
 'short_model_Chevey',
 'short_model_Chevorlet',
 'short_model_Comanche',
 'short_model_Comet',
 'short_model_D7FH173552',
 'short_model_DODGE1500',
 'short_model_Diahatsu',
 'short_model_E46',
 'short_model_EASY',
 'short_model_Eagle',
 'short_model_Emergency',
 'short_model_F-250',
 'short_model_F250',
 'short_model_FORD*',
 'short_model_FORD/RANGER',
 'short_model_FREIGHTLINER',
 'short_model_FRRV',
 'short_model_Flexible',
 'short_model_FordE350',
 'short_model_Freightliner',
 'short_model_Frtlner',
 'short_model_GCM',
 'short_model_GEHL',
 'short_model_GMC,',
 'short_model_GMX',
 'short_model_GRAND',
 'short_model_GULF',
 'short_model_Genesis',
 'short_model_Gx',
 'short_model_HINO',
 'short_model_HUMMER',
 'short_model_Hino',
 'short_model_Hobda',
 'short_model_Hot',
 'short_model_Hummer',
 'short_model_IC',
 'short_model_INTERNATIONAL',
 'short_model_International',
 'short_model_Isizu',
 'short_model_Isuzu',
 'short_model_JM1BK32F871604924',
 'short_model_Janesville',
 'short_model_Jauguar',
 'short_model_Jayco',
 'short_model_Kaiser',
 'short_model_Lotus',
 'short_model_MASERATI',
 'short_model_MERCUTY',
 'short_model_MERDECES',
 'short_model_MGB',
 'short_model_MITUSBISHI',
 'short_model_MV-1',
 'short_model_Maserati',
 'short_model_Minin',
 'short_model_Nascar',
 'short_model_OLDSMOBILE',
 'short_model_PLYMOUTH',
 'short_model_PROGRAMS',
 'short_model_Peterbilt',
 'short_model_Pierce',
 'short_model_Plymouth',
 'short_model_QX',
 'short_model_S60',
 'short_model_SCION',
 'short_model_SL',
 'short_model_Saab',
 'short_model_Scion',
 'short_model_Sea',
 'short_model_Sterling',
 'short_model_Studebaker',
 'short_model_Suzuki',
 'short_model_THOMAS',
 'short_model_Thomas',
 'short_model_Town',
 'short_model_Triumph',
 'short_model_Voltswagon',
 'short_model_Xx',
 'short_model_a-class',
 'short_model_a3',
 'short_model_a3,',
 'short_model_a4',
 'short_model_a5',
 'short_model_a6',
 'short_model_a7',
 'short_model_a8',
 'short_model_acadia',
 'short_model_accent',
 'short_model_accord',
 'short_model_all',
 'short_model_allante',
 'short_model_allroad',
 'short_model_altima',
 'short_model_am',
 'short_model_amc',
 'short_model_arcadia',
 'short_model_armada',
 'short_model_arteon',
 'short_model_ascent',
 'short_model_aspen',
 'short_model_astra',
 'short_model_astro',
 'short_model_atlas',
 'short_model_ats',
 'short_model_aura',
 'short_model_autobiography',
 'short_model_avalanche',
 'short_model_avalon',
 'short_model_avanger',
 'short_model_avenger',
 'short_model_aveo',
 'short_model_aviator',
 'short_model_azera',
 'short_model_aztek',
 'short_model_b-class',
 'short_model_b-series',
 'short_model_b2200',
 'short_model_b2300',
 'short_model_b2600i',
 'short_model_baja',
 'short_model_beetle',
 'short_model_bel',
 'short_model_belair',
 'short_model_benz',
 'short_model_blackwood',
 'short_model_blazer',
 'short_model_blue',
 'short_model_bolt',
 'short_model_bonanza',
 'short_model_bonneville',
 'short_model_boxster',
 'short_model_bronco',
 'short_model_brz',
 'short_model_bug',
 'short_model_bus',
 'short_model_c',
 'short_model_c-10',
 'short_model_c-7500',
 'short_model_c-class',
 'short_model_c-hr',
 'short_model_c-max',
 'short_model_c/k',
 'short_model_c10',
 'short_model_c250',
 'short_model_c280',
 'short_model_c30',
 'short_model_c300',
 'short_model_c4500',
 'short_model_c5500',
 'short_model_c60',
 'short_model_c6500',
 'short_model_c70',
 'short_model_c8500',
 'short_model_cabellero',
 'short_model_cabrio',
 'short_model_caddilac',
 'short_model_cadenza',
 'short_model_caliber',
 'short_model_camaro',
 'short_model_camary',
 'short_model_camero',
 'short_model_camry',
 'short_model_canyon',
 'short_model_capri',
 'short_model_caprice',
 'short_model_captiva',
 'short_model_caravan',
 'short_model_caravan/grand',
 'short_model_cargo',
 'short_model_cascada',
 'short_model_cavalier',
 'short_model_cayenne',
 'short_model_cayman',
 'short_model_cc',
 'short_model_cc300',
 'short_model_cc4500',
 'short_model_century',
 'short_model_certified',
 'short_model_challenger',
 'short_model_charger',
 'short_model_cherokee',
 'short_model_chevelle',
 'short_model_chevorlet',
 'short_model_chryler',
 'short_model_chysler',
 'short_model_city',
 'short_model_civic',
 'short_model_cj-5',
 'short_model_cj2a',
 'short_model_cj5',
 'short_model_cj7',
 'short_model_cj8',
 'short_model_cl-class',
 'short_model_cla',
 'short_model_cla-class',
 'short_model_clarity',
 'short_model_classic',
 'short_model_classuc',
 'short_model_clk',
 'short_model_clk-class',
 'short_model_clk350',
 'short_model_cls-class',
 'short_model_cls550',
 'short_model_clubman',
 'short_model_cmax',
 'short_model_cobalt',
 'short_model_colbalt',
 'short_model_colorado',
 'short_model_comet',
 'short_model_commander',
 'short_model_compass',
 'short_model_concorde',
 'short_model_conquest',
 'short_model_continental',
 'short_model_convertible',
 'short_model_cooper',
 'short_model_corolla',
 'short_model_corsair',
 'short_model_corvette',
 'short_model_cougar',
 'short_model_country',
 'short_model_countryman',
 'short_model_coupe',
 'short_model_cr-v',
 'short_model_crew',
 'short_model_crossfire',
 'short_model_crosstour',
 'short_model_crosstrek',
 'short_model_crown',
 'short_model_cruze',
 'short_model_crv',
 'short_model_crz',
 'short_model_ct',
 'short_model_ct4',
 'short_model_ct5',
 'short_model_ct6',
 'short_model_cts',
 'short_model_cts-v',
 'short_model_cts4',
 'short_model_cube',
 'short_model_cvr',
 'short_model_cx-3',
 'short_model_cx-5',
 'short_model_cx-7',
 'short_model_cx-9',
 'short_model_cx7',
 'short_model_cx9',
 'short_model_d50',
 'short_model_dakota',
 'short_model_dart',
 'short_model_davidson',
 'short_model_dealer*',
 'short_model_defender',
 'short_model_deisel',
 'short_model_deluxe',
 'short_model_denali',
 'short_model_deville',
 'short_model_diesel',
 'short_model_discovery',
 'short_model_dts',
 'short_model_dump',
 'short_model_duramax',
 'short_model_durango',
 'short_model_durangon',
 'short_model_e',
 'short_model_e-150',
 'short_model_e-250',
 'short_model_e-350',
 'short_model_e-450',
 'short_model_e-class',
 'short_model_e-golf',
 'short_model_e-pace',
 'short_model_e-series',
 'short_model_e150',
 'short_model_e250',
 'short_model_e320',
 'short_model_e350',
 'short_model_e450',
 'short_model_e46',
 'short_model_e500',
 'short_model_echo',
 'short_model_eclipse',
 'short_model_econoline',
 'short_model_ecosport',
 'short_model_edge',
 'short_model_el',
 'short_model_elantra',
 'short_model_elcamino',
 'short_model_eldorado',
 'short_model_element',
 'short_model_enclave',
 'short_model_encore',
 'short_model_endeavor',
 'short_model_envision',
 'short_model_envoy',
 'short_model_eos',
 'short_model_eqinox',
 'short_model_equinox',
 'short_model_es',
 'short_model_es300',
 'short_model_es330',
 'short_model_es350',
 'short_model_escalade',
 'short_model_escape',
 'short_model_escape-se,',
 'short_model_escort',
 'short_model_eurovan',
 'short_model_evoque',
 'short_model_excursion',
 'short_model_expedition',
 'short_model_explorer',
 'short_model_express',
 'short_model_f',
 'short_model_f-100',
 'short_model_f-150',
 'short_model_f-250',
 'short_model_f-250sd',
 'short_model_f-350',
 'short_model_f-350sd',
 'short_model_f-450',
 'short_model_f-450sd',
 'short_model_f-550',
 'short_model_f-650',
 'short_model_f-750',
 'short_model_f-pace',
 'short_model_f-type',
 'short_model_f1',
 'short_model_f100',
 'short_model_f150',
 'short_model_f250',
 'short_model_f350',
 'short_model_f450',
 'short_model_f450sd',
 'short_model_f50',
 'short_model_f550',
 'short_model_f600',
 'short_model_f650',
 'short_model_f700',
 'short_model_f750',
 'short_model_falcon',
 'short_model_fe',
 'short_model_fiero',
 'short_model_fiesta',
 'short_model_firebird',
 'short_model_fit',
 'short_model_five',
 'short_model_fj',
 'short_model_fj40',
 'short_model_fleetmaster',
 'short_model_fleetwood',
 'short_model_flex',
 'short_model_focus',
 'short_model_fords',
 'short_model_forester',
 'short_model_forte',
 'short_model_forte5',
 'short_model_foxbody',
 'short_model_freestar',
 'short_model_freestyle',
 'short_model_freightliner',
 'short_model_frontier',
 'short_model_fusion',
 'short_model_fuso',
 'short_model_fx35',
 'short_model_fx45',
 'short_model_g',
 'short_model_g-class',
 'short_model_g.',
 'short_model_g20',
 'short_model_g30',
 'short_model_g35',
 'short_model_g35x',
 'short_model_g37',
 'short_model_g37s',
 'short_model_g37x',
 'short_model_g4500',
 'short_model_g5',
 'short_model_g6',
 'short_model_g8',
 'short_model_galant',
 'short_model_genesis',
 'short_model_ghia',
 'short_model_gl',
 'short_model_gl-class',
 'short_model_gl450',
 'short_model_gla',
 'short_model_gla-class',
 'short_model_gladiator',
 'short_model_glc',
 'short_model_glc-class',
 'short_model_gle',
 'short_model_gle-class',
 'short_model_glk',
 'short_model_glk-class',
 'short_model_glk350',
 'short_model_gls',
 'short_model_gmc/chev',
 'short_model_gmce',
 'short_model_gmt-400',
 'short_model_golf',
 'short_model_gr',
 'short_model_grand',
 'short_model_grandville',
 'short_model_grumman',
 'short_model_gs',
 'short_model_gs350',
 'short_model_gs430',
 'short_model_gt',
 'short_model_gt-r',
 'short_model_gti',
 'short_model_gto',
 'short_model_gx',
 'short_model_gx460',
 'short_model_gx470',
 'short_model_hardbody',
 'short_model_hardtop',
 'short_model_hearse',
 'short_model_hhr',
 'short_model_hiace',
 'short_model_high',
 'short_model_highlander',
 'short_model_hr-v',
 'short_model_hse',
 'short_model_hummer',
 'short_model_hyndai',
 'short_model_i-miev',
 'short_model_i3',
 'short_model_i30',
 'short_model_i35',
 'short_model_ilx',
 'short_model_impala',
 'short_model_impreza',
 'short_model_insight',
 'short_model_international',
 'short_model_ion',
 'short_model_ioniq',
 'short_model_is',
 'short_model_is250',
 'short_model_is300',
 'short_model_isf',
 'short_model_isuzu',
 'short_model_jeepster',
 'short_model_jetta',
 'short_model_jimmy',
 'short_model_jouney',
 'short_model_journey',
 'short_model_juke',
 'short_model_jx35',
 'short_model_k10',
 'short_model_k20',
 'short_model_k30',
 'short_model_k5',
 'short_model_k900',
 'short_model_kicks',
 'short_model_kodiak',
 'short_model_l',
 'short_model_l300',
 'short_model_lacrosse',
 'short_model_lancer',
 'short_model_land',
 'short_model_landcruiser',
 'short_model_leaf',
 'short_model_legacy',
 'short_model_legend',
 'short_model_lemans',
 'short_model_lesabre',
 'short_model_liberty',
 'short_model_lifted',
 'short_model_lightning',
 'short_model_limousine',
 'short_model_long',
 'short_model_lr2',
 'short_model_lr3',
 'short_model_lr4',
 'short_model_ls',
 'short_model_ltd',
 'short_model_lucerne',
 'short_model_lx',
 'short_model_lx450',
 'short_model_m',
 'short_model_m-class',
 'short_model_m3',
 'short_model_m35',
 'short_model_m35s',
 'short_model_m5',
 'short_model_macan',
 'short_model_magnum',
 'short_model_malibu',
 'short_model_mallinia',
 'short_model_marineer,premier',
 'short_model_mariner',
 'short_model_mark',
 'short_model_maserati',
 'short_model_matrix',
 'short_model_maxima',
 'short_model_maximum',
 'short_model_mazda2',
 'short_model_mazda3',
 'short_model_mazda5',
 'short_model_mazda6',
 'short_model_mazda6i',
 'short_model_md-x',
 'short_model_mdx',
 'short_model_mercades',
 'short_model_mercedes-amg',
 'short_model_metris',
 'short_model_mg',
 'short_model_miata',
 'short_model_milan',
 'short_model_mirage',
 'short_model_mkc',
 'short_model_mks',
 'short_model_mkt',
 'short_model_mkx',
 'short_model_mkz',
 'short_model_ml',
 'short_model_ml350',
 'short_model_ml500',
 'short_model_model',
 'short_model_monte',
 'short_model_montero',
 'short_model_mountaineer',
 'short_model_mpv',
 'short_model_mr2',
 'short_model_murano',
 'short_model_mustang',
 'short_model_mx-5',
 'short_model_nautilus',
 'short_model_navigator',
 'short_model_neon',
 'short_model_new',
 'short_model_newport',
 'short_model_niro',
 'short_model_nitro',
 'short_model_nova',
 'short_model_nv',
 'short_model_nv1500',
 'short_model_nv200',
 'short_model_nv2500',
 'short_model_nv2500hd',
 'short_model_nx',
 'short_model_nx300',
 'short_model_oddyssey',
 'short_model_odyssey',
 'short_model_oldsmobile',
 'short_model_optima',
 'short_model_optimia',
 'short_model_other',
 'short_model_outback',
 'short_model_outlander',
 'short_model_outlook',
 'short_model_paceman',
 'short_model_pacifica',
 'short_model_panamera',
 'short_model_panel',
 'short_model_park',
 'short_model_passat',
 'short_model_passport',
 'short_model_pathfinder',
 'short_model_patriot',
 'short_model_phaeton',
 'short_model_pick',
 'short_model_pickup',
 'short_model_pilot',
 'short_model_plymouth',
 'short_model_pontaic',
 'short_model_prelude',
 'short_model_prius',
 'short_model_prizm',
 'short_model_promaster',
 'short_model_protege',
 'short_model_pt',
 'short_model_putback',
 'short_model_q3',
 'short_model_q5',
 'short_model_q50',
 'short_model_q60',
 'short_model_q7',
 'short_model_q70',
 'short_model_quattro',
 'short_model_quest',
 'short_model_qx50',
 'short_model_qx56',
 'short_model_qx60',
 'short_model_qx70',
 'short_model_qx80',
 'short_model_r-class',
 'short_model_r32',
 'short_model_rabbit',
 'short_model_rainier',
 'short_model_ram1500',
 'short_model_ram2500',
 'short_model_ramcharger',
 'short_model_range',
 'short_model_ranger',
 'short_model_rat',
 'short_model_rav',
 'short_model_rav4',
 'short_model_rc',
 'short_model_rdx',
 'short_model_reatta',
 'short_model_rebel',
 'short_model_regal',
 'short_model_rendezvous',
 'short_model_renegade',
 'short_model_replica',
 'short_model_ridgeline',
 'short_model_rio',
 'short_model_rivera',
 'short_model_riviera',
 'short_model_rl',
 'short_model_rlx',
 'short_model_roadmaster',
 'short_model_roadster',
 'short_model_rogue',
 'short_model_romeo',
 'short_model_rondo',
 'short_model_rouge',
 'short_model_routan',
 'short_model_rs',
 'short_model_rsx',
 'short_model_rx',
 'short_model_rx-8',
 'short_model_rx300',
 'short_model_rx330',
 'short_model_rx350',
 'short_model_rx400h',
 'short_model_rx7',
 'short_model_rx8',
 'short_model_s',
 'short_model_s-10',
 'short_model_s-class',
 'short_model_s/w',
 'short_model_s10',
 'short_model_s2000',
 'short_model_s3',
 'short_model_s320',
 'short_model_s4',
 'short_model_s40',
 'short_model_s430',
 'short_model_s5',
 'short_model_s500',
 'short_model_s6',
 'short_model_s60',
 'short_model_s7',
 'short_model_s70',
 'short_model_s8',
 'short_model_s90',
 'short_model_saab',
 'short_model_sable',
 'short_model_santa',
 'short_model_sante',
 'short_model_savana',
 'short_model_sc',
 'short_model_sc2',
 'short_model_sc300',
 'short_model_school',
 'short_model_scion',
 'short_model_sebring',
 'short_model_sedan',
 'short_model_sedona',
 'short_model_seirra',
 'short_model_sentra',
 'short_model_sequioa',
 'short_model_sequoia',
 'short_model_seville',
 'short_model_shelby',
 'short_model_sienna',
 'short_model_sierra',
 'short_model_sierra1500',
 'short_model_silverado',
 'short_model_sky',
 'short_model_skylark',
 'short_model_sl-class',
 'short_model_sl2',
 'short_model_sl500',
 'short_model_sl55',
 'short_model_sl550',
 'short_model_slc',
 'short_model_sle',
 'short_model_slk',
 'short_model_slk-class',
 'short_model_slt',
 'short_model_smart',
 'short_model_solara',
 'short_model_solstice',
 'short_model_sonata',
 'short_model_sonic',
 'short_model_sonoma',
 'short_model_sorento',
 'short_model_sorrento',
 'short_model_soul',
 'short_model_soul+',
 'short_model_spark',
 'short_model_spectra',
 'short_model_sport',
 'short_model_sportage',
 'short_model_sprinter',
 'short_model_srx',
 'short_model_srx-v6',
 'short_model_srx4',
 'short_model_srx~awesome',
 'short_model_ss',
 'short_model_ssr',
 'short_model_starcraft',
 'short_model_step-van',
 'short_model_stinger',
 'short_model_stratus',
 'short_model_sts',
 'short_model_studebaker',
 'short_model_suburban',
 'short_model_super',
 'short_model_supra',
 'short_model_suv',
 'short_model_suzuki',
 'short_model_svx',
 'short_model_t',
 'short_model_t-350',
 'short_model_t-bucket',
 'short_model_tacoma',
 'short_model_tahoe',
 'short_model_tarsus',
 'short_model_taurus',
 'short_model_tc5500',
 'short_model_telluride',
 'short_model_tercel',
 'short_model_terrain',
 'short_model_thing',
 'short_model_thomas',
 'short_model_thrift',
 'short_model_thunderbird',
 'short_model_tiguan',
 'short_model_titan',
 'short_model_tl',
 'short_model_tlx',
 'short_model_torrent',
 'short_model_touareg',
 'short_model_town',
 'short_model_tracker',
 'short_model_tractor',
 'short_model_trailblazer',
 'short_model_trans',
 'short_model_transit',
 'short_model_traverse',
 'short_model_trax',
 'short_model_tribeca',
 'short_model_tribute',
 'short_model_triumph',
 'short_model_truck',
 'short_model_tsx',
 'short_model_tt',
 'short_model_tucson',
 'short_model_tudor',
 'short_model_tundra',
 'short_model_uplander',
 'short_model_utility',
 'short_model_ux',
 'short_model_v50',

In [97]:
df_prepared.shape

(9619, 1470)

3. Запишите преобразованный датафрейм в файл `data/vehicles_dataset_prepared.csv`, индекс не сохраняйте.

In [99]:
# Ваш код здесь
df_prepared.to_csv('data/vehicles_dataset_prepared.csv', index=False)

## Описание преобразованного датасета:
- `id`— идентификатор записи;
- `is_manufacturer_name`— признак производителя автомобиля;

- `region_*`— регион;
- `x0_*`— тип топлива;
- `manufacturer_*`— производитель;
- `short_model_*`— сокращённая модель автомобиля;
- `title_status_*`— статус;
- `transmission_*`— коробка передач;
- `state_*`— штат;
- `age_category_*`— возрастная категория автомобиля;

- `std_scaled_odometer`— количество пройденных миль (после стандартизации);
- `year_std`— год выпуска (после стандартизации);
- `lat_std`— широта (после стандартизации);
- `long_std`— долгота (после стандартизации);
- `odometer/price_std`— отношение стоимости к пробегу автомобиля (после стандартизации);
- `desc_len_std`— количество символов в тексте объявления о продаже (после стандартизации);
- `model_in_desc_std`— количество наименований модели автомобиля в тексте объявления о продаже (после стандартизации);
- `model_len_std`— длина наименования автомобиля (после стандартизации);
- `model_word_count_std`— количество слов в наименовании автомобиля (после стандартизации);
- `month_std`— номер месяца размещения объявления о продаже автомобиля (после стандартизации);
- `dayofweek_std`— день недели размещения объявления о продаже автомобиля (после стандартизации);
- `diff_years_std`— количество лет между годом производства автомобиля и годом размещения объявления о продаже автомобиля (после стандартизации);

- `price`— стоимость;
- `price_category`– категория цены.